// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IncrementalMerkleTree} from "./libraries/IncrementalMerkleTree.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title IVerifier
 * @notice Interface for Groth16 proof verification (snarkjs-generated).
 */
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title DenominatedPool
 * @notice Fixed-denomination privacy pool for native tokens (e.g. TAO, ETH).
 *
 *         Unlike ShieldedPool which accepts arbitrary deposit amounts,
 *         DenominatedPool enforces a fixed deposit size (e.g. 0.1 TAO,
 *         1 TAO, 10 TAO). Every deposit is identical, creating larger
 *         anonymity sets — an observer cannot correlate deposits and
 *         withdrawals by matching amounts.
 *
 *         Follows the Tornado Cash model: deposit exactly `denomination`,
 *         withdraw exactly `denomination` (minus protocol fee).
 *
 *         Uses Poseidon-based incremental Merkle tree and Groth16 ZK proofs
 *         (same as ShieldedPool).
 */
contract DenominatedPool is ReentrancyGuard {
    using IncrementalMerkleTree for IncrementalMerkleTree.Tree;

    // ---------------------------------------------------------------
    // Storage
    // ---------------------------------------------------------------

    IncrementalMerkleTree.Tree private tree;

    /// @notice The Groth16 verifier contract (auto-generated by snarkjs)
    IVerifier public immutable verifier;

    /// @notice Fixed deposit amount (e.g., 0.1 TAO, 1 TAO, 10 TAO)
    uint256 public immutable denomination;

    /// @notice Tracks which commitments have been inserted (prevents duplicates)
    mapping(bytes32 => bool) public commitments;

    /// @notice Tracks which nullifiers have been spent (prevents double-spend)
    mapping(bytes32 => bool) public nullifierHashes;

    uint32 public immutable levels;

    // ---------------------------------------------------------------
    // Protocol Fee
    // ---------------------------------------------------------------

    /// @notice Fee recipient (protocol treasury)
    address payable public feeRecipient;

    /// @notice Fee in basis points (50 = 0.5%)
    uint256 public feeBasisPoints;

    /// @notice Maximum fee: 2% (200 basis points)
    uint256 public constant MAX_FEE_BPS = 200;

    /// @notice Contract owner (can update fee params)
    address public owner;

    /// @notice Total fees collected (native token only, address(0) key)
    mapping(address => uint256) public feesCollected;

    // ---------------------------------------------------------------
    // Events
    // ---------------------------------------------------------------

    event Deposit(
        bytes32 indexed commitment,
        uint32 leafIndex,
        uint256 timestamp
    );

    event Withdrawal(
        bytes32 indexed nullifierHash,
        address recipient,
        uint256 amount
    );

    event FeeCollected(
        address indexed token,
        uint256 amount,
        address indexed recipient
    );

    event FeeUpdated(uint256 newFeeBps);
    event FeeRecipientUpdated(address newRecipient);
    event OwnerTransferred(address newOwner);

    // ---------------------------------------------------------------
    // Modifiers
    // ---------------------------------------------------------------

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    // ---------------------------------------------------------------
    // Constructor
    // ---------------------------------------------------------------

    /**
     * @param _levels        Merkle tree depth (20 ~ 1M deposits)
     * @param _verifier      Address of the deployed Groth16Verifier contract
     * @param _denomination  Fixed deposit amount in wei
     * @param _feeRecipient  Address to receive protocol fees
     * @param _feeBps        Fee in basis points (50 = 0.5%)
     */
    constructor(
        uint32 _levels,
        IVerifier _verifier,
        uint256 _denomination,
        address payable _feeRecipient,
        uint256 _feeBps
    ) {
        require(address(_verifier) != address(0), "Invalid verifier address");
        require(_denomination > 0, "Denomination must be > 0");
        require(_feeRecipient != address(0), "Invalid fee recipient");
        require(_feeBps <= MAX_FEE_BPS, "Fee too high");

        levels = _levels;
        verifier = _verifier;
        denomination = _denomination;
        feeRecipient = _feeRecipient;
        feeBasisPoints = _feeBps;
        owner = msg.sender;
        tree.init(_levels);
    }

    // ---------------------------------------------------------------
    // Fee Management
    // ---------------------------------------------------------------

    /**
     * @notice Update the protocol fee (owner only).
     * @param _newFeeBps New fee in basis points (max 200 = 2%)
     */
    function setFee(uint256 _newFeeBps) external onlyOwner {
        require(_newFeeBps <= MAX_FEE_BPS, "Fee too high");
        feeBasisPoints = _newFeeBps;
        emit FeeUpdated(_newFeeBps);
    }

    /**
     * @notice Update the fee recipient address (owner only).
     * @param _newRecipient New fee recipient address
     */
    function setFeeRecipient(address payable _newRecipient) external onlyOwner {
        require(_newRecipient != address(0), "Invalid fee recipient");
        feeRecipient = _newRecipient;
        emit FeeRecipientUpdated(_newRecipient);
    }

    /**
     * @notice Transfer ownership (owner only).
     * @param _newOwner New owner address
     */
    function transferOwnership(address _newOwner) external onlyOwner {
        require(_newOwner != address(0), "Invalid owner");
        owner = _newOwner;
        emit OwnerTransferred(_newOwner);
    }

    /**
     * @dev Calculate the fee amount for a given value.
     */
    function _calculateFee(uint256 _amount) internal view returns (uint256) {
        if (feeBasisPoints == 0) return 0;
        return (_amount * feeBasisPoints) / 10000;
    }

    // ---------------------------------------------------------------
    // Deposit (Shield)
    // ---------------------------------------------------------------

    /**
     * @notice Deposit exactly `denomination` amount of native token.
     *         msg.value must equal the denomination exactly.
     *         The full amount is held by the pool — fees are only
     *         deducted on withdrawal, ensuring the pool always has
     *         enough to cover each withdrawal.
     * @param _commitment The commitment hash (hiding nullifier + secret)
     */
    function deposit(bytes32 _commitment) external payable nonReentrant {
        require(msg.value == denomination, "Must deposit exact denomination");
        require(_commitment != bytes32(0), "Invalid commitment");
        require(!commitments[_commitment], "Duplicate commitment");

        commitments[_commitment] = true;

        (, uint32 leafIndex) = tree.insert(_commitment);

        emit Deposit(_commitment, leafIndex, block.timestamp);
    }

    // ---------------------------------------------------------------
    // Withdraw (Unshield)
    // ---------------------------------------------------------------

    /**
     * @notice Withdraw the denomination amount using a ZK proof.
     *         Always withdraws exactly `denomination` (minus protocol fee).
     *         No amount parameter — the denomination is implicit.
     * @param _nullifierHash  The nullifier hash (derived from note secret)
     * @param _recipient      Address to receive the funds
     * @param _root           The Merkle root to verify against
     * @param _proof          ABI-encoded Groth16 proof (pA, pB, pC)
     */
    function withdraw(
        bytes32 _nullifierHash,
        address payable _recipient,
        bytes32 _root,
        bytes calldata _proof
    ) external nonReentrant {
        require(!nullifierHashes[_nullifierHash], "Nullifier already spent");
        require(tree.isKnownRoot(_root), "Unknown Merkle root");
        require(
            _verifyProof(
                _proof,
                _nullifierHash,
                _root,
                _recipient,
                denomination
            ),
            "Invalid proof"
        );

        // Mark nullifier as spent
        nullifierHashes[_nullifierHash] = true;

        // Calculate fee
        uint256 fee = _calculateFee(denomination);
        uint256 netAmount = denomination - fee;

        // Send fee to protocol treasury
        if (fee > 0) {
            (bool feeSuccess, ) = feeRecipient.call{value: fee}("");
            require(feeSuccess, "Fee transfer failed");
            feesCollected[address(0)] += fee;
            emit FeeCollected(address(0), fee, feeRecipient);
        }

        // Send net amount to recipient
        (bool success, ) = _recipient.call{value: netAmount}("");
        require(success, "Transfer failed");

        emit Withdrawal(_nullifierHash, _recipient, denomination);
    }

    // ---------------------------------------------------------------
    // View functions
    // ---------------------------------------------------------------

    /**
     * @notice Get the latest Merkle root.
     */
    function getLatestRoot() external view returns (bytes32) {
        return tree.getLatestRoot();
    }

    /**
     * @notice Check if a root exists in the recent root history.
     */
    function isKnownRoot(bytes32 _root) external view returns (bool) {
        return tree.isKnownRoot(_root);
    }

    /**
     * @notice Check if a nullifier has been spent.
     */
    function isSpentNullifier(
        bytes32 _nullifierHash
    ) external view returns (bool) {
        return nullifierHashes[_nullifierHash];
    }

    /**
     * @notice Get the next leaf index (= number of deposits so far).
     */
    function getNextIndex() external view returns (uint32) {
        return tree.nextIndex;
    }

    // ---------------------------------------------------------------
    // Internal — Proof verification
    // ---------------------------------------------------------------

    /**
     * @dev Verify a Groth16 ZK proof using the deployed verifier contract.
     */
    function _verifyProof(
        bytes calldata _proof,
        bytes32 _nullifierHash,
        bytes32 _root,
        address _recipient,
        uint256 _amount
    ) internal view returns (bool) {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = abi.decode(
            _proof,
            (uint[2], uint[2][2], uint[2])
        );

        uint[4] memory pubSignals = [
            uint256(_root),
            uint256(_nullifierHash),
            uint256(uint160(_recipient)),
            _amount
        ];

        return verifier.verifyProof(pA, pB, pC, pubSignals);
    }

    // Allow contract to receive ETH (for direct transfers / top-ups)
    receive() external payable {}
}
