// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IncrementalMerkleTree} from "./libraries/IncrementalMerkleTree.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

/**
 * @title IVerifier
 * @notice Interface for Groth16 proof verification (snarkjs-generated).
 */
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title ShieldedPool
 * @notice Privacy pool for ETH and ERC-20 tokens.
 *
 *         Deposits insert a commitment into an incremental Merkle tree
 *         using Poseidon hashing (SNARK-friendly, matches circomlib).
 *         Withdrawals consume a nullifier (preventing double-spend),
 *         verify a Groth16 ZK proof, and send funds to the recipient.
 *
 *         The proof demonstrates that the withdrawer knows a secret
 *         (nullifier, secret) corresponding to a commitment in the tree,
 *         without revealing which commitment.
 */
contract ShieldedPool is ReentrancyGuard {
    using IncrementalMerkleTree for IncrementalMerkleTree.Tree;
    using SafeERC20 for IERC20;

    // ---------------------------------------------------------------
    // Storage
    // ---------------------------------------------------------------

    IncrementalMerkleTree.Tree private tree;

    /// @notice The Groth16 verifier contract (auto-generated by snarkjs)
    IVerifier public immutable verifier;

    /// @notice Tracks which commitments have been inserted (prevents duplicates)
    mapping(bytes32 => bool) public commitments;

    /// @notice Tracks which nullifiers have been spent (prevents double-spend)
    mapping(bytes32 => bool) public nullifierHashes;

    /// @notice ETH balance deposited per-address is not tracked — pool is anonymous.
    ///         Total pool balance is simply address(this).balance for ETH.

    /// @notice ERC-20 balances held by the pool, keyed by token address
    mapping(address => uint256) public tokenBalances;

    uint32 public immutable levels;

    // ---------------------------------------------------------------
    // Events
    // ---------------------------------------------------------------

    event Deposit(
        bytes32 indexed commitment,
        uint32 leafIndex,
        uint256 timestamp
    );

    event Withdrawal(
        bytes32 indexed nullifierHash,
        address recipient,
        uint256 amount
    );

    // ---------------------------------------------------------------
    // Constructor
    // ---------------------------------------------------------------

    /**
     * @param _levels   Merkle tree depth (20 ≈ 1M deposits)
     * @param _verifier Address of the deployed Groth16Verifier contract
     */
    constructor(uint32 _levels, IVerifier _verifier) {
        require(address(_verifier) != address(0), "Invalid verifier address");
        levels = _levels;
        verifier = _verifier;
        tree.init(_levels);
    }

    // ---------------------------------------------------------------
    // Deposit (Shield)
    // ---------------------------------------------------------------

    /**
     * @notice Deposit ETH into the shielded pool.
     * @param _commitment The commitment hash (hiding amount + blinding factor)
     */
    function deposit(bytes32 _commitment) external payable nonReentrant {
        require(msg.value > 0, "Deposit amount must be > 0");
        require(_commitment != bytes32(0), "Invalid commitment");
        require(!commitments[_commitment], "Duplicate commitment");

        commitments[_commitment] = true;

        (, uint32 leafIndex) = tree.insert(_commitment);

        emit Deposit(_commitment, leafIndex, block.timestamp);
    }

    /**
     * @notice Deposit ERC-20 tokens into the shielded pool.
     * @param _commitment  The commitment hash
     * @param _token       ERC-20 token address
     * @param _amount      Amount of tokens to deposit
     */
    function depositERC20(
        bytes32 _commitment,
        address _token,
        uint256 _amount
    ) external nonReentrant {
        require(_amount > 0, "Deposit amount must be > 0");
        require(_commitment != bytes32(0), "Invalid commitment");
        require(!commitments[_commitment], "Duplicate commitment");
        require(_token != address(0), "Invalid token address");

        // Transfer tokens from sender to pool
        IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);
        tokenBalances[_token] += _amount;

        commitments[_commitment] = true;

        (, uint32 leafIndex) = tree.insert(_commitment);

        emit Deposit(_commitment, leafIndex, block.timestamp);
    }

    // ---------------------------------------------------------------
    // Withdraw (Unshield)
    // ---------------------------------------------------------------

    /**
     * @notice Withdraw funds from the pool using a nullifier.
     * @param _nullifierHash  The nullifier hash (derived from note secret)
     * @param _recipient      Address to receive the funds
     * @param _amount         Amount to withdraw
     * @param _token          Token address (address(0) for ETH)
     * @param _root           The Merkle root to verify against
     * @param _proof          ABI-encoded Groth16 proof (pA, pB, pC)
     */
    function withdraw(
        bytes32 _nullifierHash,
        address payable _recipient,
        uint256 _amount,
        address _token,
        bytes32 _root,
        bytes calldata _proof
    ) external nonReentrant {
        require(_amount > 0, "Withdrawal amount must be > 0");
        require(!nullifierHashes[_nullifierHash], "Nullifier already spent");
        require(tree.isKnownRoot(_root), "Unknown Merkle root");
        require(
            _verifyProof(
                _proof,
                _nullifierHash,
                _root,
                _recipient,
                _amount
            ),
            "Invalid proof"
        );

        // Mark nullifier as spent
        nullifierHashes[_nullifierHash] = true;

        // Transfer funds
        if (_token == address(0)) {
            // ETH withdrawal
            require(
                address(this).balance >= _amount,
                "Insufficient ETH in pool"
            );
            (bool success, ) = _recipient.call{value: _amount}("");
            require(success, "ETH transfer failed");
        } else {
            // ERC-20 withdrawal
            require(
                tokenBalances[_token] >= _amount,
                "Insufficient token balance in pool"
            );
            tokenBalances[_token] -= _amount;
            IERC20(_token).safeTransfer(_recipient, _amount);
        }

        emit Withdrawal(_nullifierHash, _recipient, _amount);
    }

    // ---------------------------------------------------------------
    // View functions
    // ---------------------------------------------------------------

    /**
     * @notice Get the latest Merkle root.
     */
    function getLatestRoot() external view returns (bytes32) {
        return tree.getLatestRoot();
    }

    /**
     * @notice Check if a root exists in the recent root history.
     */
    function isKnownRoot(bytes32 _root) external view returns (bool) {
        return tree.isKnownRoot(_root);
    }

    /**
     * @notice Check if a nullifier has been spent.
     */
    function isSpentNullifier(
        bytes32 _nullifierHash
    ) external view returns (bool) {
        return nullifierHashes[_nullifierHash];
    }

    /**
     * @notice Get the next leaf index (= number of deposits so far).
     */
    function getNextIndex() external view returns (uint32) {
        return tree.nextIndex;
    }

    // ---------------------------------------------------------------
    // Internal — Proof verification
    // ---------------------------------------------------------------

    /**
     * @dev Verify a Groth16 ZK proof using the deployed verifier contract.
     *
     *      The proof demonstrates that the prover:
     *      1. Knows (nullifier, secret) such that Poseidon(nullifier, secret) = commitment
     *      2. The commitment is a leaf in the Merkle tree under the given root
     *      3. Poseidon(nullifier) = nullifierHash
     *      4. The recipient and amount are bound to the proof (anti-front-running)
     *
     * @param _proof          ABI-encoded Groth16 proof: (uint[2] pA, uint[2][2] pB, uint[2] pC)
     * @param _nullifierHash  Public input: Poseidon(nullifier)
     * @param _root           Public input: Merkle root
     * @param _recipient      Public input: withdrawal recipient address
     * @param _amount         Public input: withdrawal amount
     */
    function _verifyProof(
        bytes calldata _proof,
        bytes32 _nullifierHash,
        bytes32 _root,
        address _recipient,
        uint256 _amount
    ) internal view returns (bool) {
        // Decode Groth16 proof components from the ABI-encoded bytes
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = abi.decode(
            _proof,
            (uint[2], uint[2][2], uint[2])
        );

        // Public signals must match the circuit's public input order:
        // [root, nullifierHash, recipient, amount]
        uint[4] memory pubSignals = [
            uint256(_root),
            uint256(_nullifierHash),
            uint256(uint160(_recipient)),
            _amount
        ];

        return verifier.verifyProof(pA, pB, pC, pubSignals);
    }

    // Allow contract to receive ETH
    receive() external payable {}
}
