// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IncrementalMerkleTree} from "./libraries/IncrementalMerkleTree.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

/**
 * @title IVerifier
 * @notice Interface for Groth16 proof verification (snarkjs-generated).
 */
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title ShieldedPool
 * @notice Privacy pool for ETH and ERC-20 tokens with protocol fee.
 *
 *         Deposits insert a commitment into an incremental Merkle tree
 *         using Poseidon hashing (SNARK-friendly, matches circomlib).
 *         Withdrawals consume a nullifier (preventing double-spend),
 *         verify a Groth16 ZK proof, and send funds to the recipient.
 *
 *         A protocol fee (in basis points) is deducted on both deposits
 *         and withdrawals, sent to the fee recipient address.
 */
contract ShieldedPool is ReentrancyGuard {
    using IncrementalMerkleTree for IncrementalMerkleTree.Tree;
    using SafeERC20 for IERC20;

    // ---------------------------------------------------------------
    // Storage
    // ---------------------------------------------------------------

    IncrementalMerkleTree.Tree private tree;

    /// @notice The Groth16 verifier contract (auto-generated by snarkjs)
    IVerifier public immutable verifier;

    /// @notice Tracks which commitments have been inserted (prevents duplicates)
    mapping(bytes32 => bool) public commitments;

    /// @notice Tracks which nullifiers have been spent (prevents double-spend)
    mapping(bytes32 => bool) public nullifierHashes;

    /// @notice ERC-20 balances held by the pool, keyed by token address
    mapping(address => uint256) public tokenBalances;

    uint32 public immutable levels;

    // ---------------------------------------------------------------
    // Protocol Fee
    // ---------------------------------------------------------------

    /// @notice Fee recipient (protocol treasury)
    address payable public feeRecipient;

    /// @notice Fee in basis points (50 = 0.5%)
    uint256 public feeBasisPoints;

    /// @notice Maximum fee: 2% (200 basis points)
    uint256 public constant MAX_FEE_BPS = 200;

    /// @notice Contract owner (can update fee params)
    address public owner;

    /// @notice Total fees collected per token (address(0) for native)
    mapping(address => uint256) public feesCollected;

    // ---------------------------------------------------------------
    // Events
    // ---------------------------------------------------------------

    event Deposit(
        bytes32 indexed commitment,
        uint32 leafIndex,
        uint256 timestamp
    );

    event Withdrawal(
        bytes32 indexed nullifierHash,
        address recipient,
        uint256 amount
    );

    event FeeCollected(
        address indexed token,
        uint256 amount,
        address indexed recipient
    );

    event FeeUpdated(uint256 newFeeBps);
    event FeeRecipientUpdated(address newRecipient);
    event OwnerTransferred(address newOwner);

    // ---------------------------------------------------------------
    // Modifiers
    // ---------------------------------------------------------------

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    // ---------------------------------------------------------------
    // Constructor
    // ---------------------------------------------------------------

    /**
     * @param _levels        Merkle tree depth (20 ~ 1M deposits)
     * @param _verifier      Address of the deployed Groth16Verifier contract
     * @param _feeRecipient  Address to receive protocol fees
     * @param _feeBps        Fee in basis points (50 = 0.5%)
     */
    constructor(
        uint32 _levels,
        IVerifier _verifier,
        address payable _feeRecipient,
        uint256 _feeBps
    ) {
        require(address(_verifier) != address(0), "Invalid verifier address");
        require(_feeRecipient != address(0), "Invalid fee recipient");
        require(_feeBps <= MAX_FEE_BPS, "Fee too high");

        levels = _levels;
        verifier = _verifier;
        feeRecipient = _feeRecipient;
        feeBasisPoints = _feeBps;
        owner = msg.sender;
        tree.init(_levels);
    }

    // ---------------------------------------------------------------
    // Fee Management
    // ---------------------------------------------------------------

    /**
     * @notice Update the protocol fee (owner only).
     * @param _newFeeBps New fee in basis points (max 200 = 2%)
     */
    function setFee(uint256 _newFeeBps) external onlyOwner {
        require(_newFeeBps <= MAX_FEE_BPS, "Fee too high");
        feeBasisPoints = _newFeeBps;
        emit FeeUpdated(_newFeeBps);
    }

    /**
     * @notice Update the fee recipient address (owner only).
     * @param _newRecipient New fee recipient address
     */
    function setFeeRecipient(address payable _newRecipient) external onlyOwner {
        require(_newRecipient != address(0), "Invalid fee recipient");
        feeRecipient = _newRecipient;
        emit FeeRecipientUpdated(_newRecipient);
    }

    /**
     * @notice Transfer ownership (owner only).
     * @param _newOwner New owner address
     */
    function transferOwnership(address _newOwner) external onlyOwner {
        require(_newOwner != address(0), "Invalid owner");
        owner = _newOwner;
        emit OwnerTransferred(_newOwner);
    }

    /**
     * @dev Calculate the fee amount for a given value.
     */
    function _calculateFee(uint256 _amount) internal view returns (uint256) {
        if (feeBasisPoints == 0) return 0;
        return (_amount * feeBasisPoints) / 10000;
    }

    // ---------------------------------------------------------------
    // Deposit (Shield)
    // ---------------------------------------------------------------

    /**
     * @notice Deposit ETH into the shielded pool.
     *         A protocol fee is deducted and sent to the fee recipient.
     * @param _commitment The commitment hash (hiding amount + blinding factor)
     */
    function deposit(bytes32 _commitment) external payable nonReentrant {
        require(msg.value > 0, "Deposit amount must be > 0");
        require(_commitment != bytes32(0), "Invalid commitment");
        require(!commitments[_commitment], "Duplicate commitment");

        // Calculate and transfer fee
        uint256 fee = _calculateFee(msg.value);
        if (fee > 0) {
            (bool feeSuccess, ) = feeRecipient.call{value: fee}("");
            require(feeSuccess, "Fee transfer failed");
            feesCollected[address(0)] += fee;
            emit FeeCollected(address(0), fee, feeRecipient);
        }

        commitments[_commitment] = true;

        (, uint32 leafIndex) = tree.insert(_commitment);

        emit Deposit(_commitment, leafIndex, block.timestamp);
    }

    /**
     * @notice Deposit ERC-20 tokens into the shielded pool.
     *         A protocol fee is deducted and sent to the fee recipient.
     * @param _commitment  The commitment hash
     * @param _token       ERC-20 token address
     * @param _amount      Amount of tokens to deposit
     */
    function depositERC20(
        bytes32 _commitment,
        address _token,
        uint256 _amount
    ) external nonReentrant {
        require(_amount > 0, "Deposit amount must be > 0");
        require(_commitment != bytes32(0), "Invalid commitment");
        require(!commitments[_commitment], "Duplicate commitment");
        require(_token != address(0), "Invalid token address");

        // Transfer full amount from sender to pool
        IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);

        // Calculate and transfer fee
        uint256 fee = _calculateFee(_amount);
        if (fee > 0) {
            IERC20(_token).safeTransfer(feeRecipient, fee);
            feesCollected[_token] += fee;
            emit FeeCollected(_token, fee, feeRecipient);
        }

        tokenBalances[_token] += (_amount - fee);

        commitments[_commitment] = true;

        (, uint32 leafIndex) = tree.insert(_commitment);

        emit Deposit(_commitment, leafIndex, block.timestamp);
    }

    // ---------------------------------------------------------------
    // Withdraw (Unshield)
    // ---------------------------------------------------------------

    /**
     * @notice Withdraw funds from the pool using a nullifier.
     *         A protocol fee is deducted from the withdrawal amount.
     * @param _nullifierHash  The nullifier hash (derived from note secret)
     * @param _recipient      Address to receive the funds
     * @param _amount         Amount to withdraw (before fee deduction)
     * @param _token          Token address (address(0) for ETH)
     * @param _root           The Merkle root to verify against
     * @param _proof          ABI-encoded Groth16 proof (pA, pB, pC)
     */
    function withdraw(
        bytes32 _nullifierHash,
        address payable _recipient,
        uint256 _amount,
        address _token,
        bytes32 _root,
        bytes calldata _proof
    ) external nonReentrant {
        require(_amount > 0, "Withdrawal amount must be > 0");
        require(!nullifierHashes[_nullifierHash], "Nullifier already spent");
        require(tree.isKnownRoot(_root), "Unknown Merkle root");
        require(
            _verifyProof(
                _proof,
                _nullifierHash,
                _root,
                _recipient,
                _amount
            ),
            "Invalid proof"
        );

        // Mark nullifier as spent
        nullifierHashes[_nullifierHash] = true;

        // Calculate fee
        uint256 fee = _calculateFee(_amount);
        uint256 netAmount = _amount - fee;

        // Transfer funds
        if (_token == address(0)) {
            // ETH withdrawal
            require(
                address(this).balance >= _amount,
                "Insufficient ETH in pool"
            );

            // Send fee to protocol treasury
            if (fee > 0) {
                (bool feeSuccess, ) = feeRecipient.call{value: fee}("");
                require(feeSuccess, "Fee transfer failed");
                feesCollected[address(0)] += fee;
                emit FeeCollected(address(0), fee, feeRecipient);
            }

            // Send net amount to recipient
            (bool success, ) = _recipient.call{value: netAmount}("");
            require(success, "ETH transfer failed");
        } else {
            // ERC-20 withdrawal
            require(
                tokenBalances[_token] >= _amount,
                "Insufficient token balance in pool"
            );
            tokenBalances[_token] -= _amount;

            // Send fee to protocol treasury
            if (fee > 0) {
                IERC20(_token).safeTransfer(feeRecipient, fee);
                feesCollected[_token] += fee;
                emit FeeCollected(_token, fee, feeRecipient);
            }

            // Send net amount to recipient
            IERC20(_token).safeTransfer(_recipient, netAmount);
        }

        emit Withdrawal(_nullifierHash, _recipient, _amount);
    }

    // ---------------------------------------------------------------
    // View functions
    // ---------------------------------------------------------------

    /**
     * @notice Get the latest Merkle root.
     */
    function getLatestRoot() external view returns (bytes32) {
        return tree.getLatestRoot();
    }

    /**
     * @notice Check if a root exists in the recent root history.
     */
    function isKnownRoot(bytes32 _root) external view returns (bool) {
        return tree.isKnownRoot(_root);
    }

    /**
     * @notice Check if a nullifier has been spent.
     */
    function isSpentNullifier(
        bytes32 _nullifierHash
    ) external view returns (bool) {
        return nullifierHashes[_nullifierHash];
    }

    /**
     * @notice Get the next leaf index (= number of deposits so far).
     */
    function getNextIndex() external view returns (uint32) {
        return tree.nextIndex;
    }

    // ---------------------------------------------------------------
    // Internal — Proof verification
    // ---------------------------------------------------------------

    /**
     * @dev Verify a Groth16 ZK proof using the deployed verifier contract.
     */
    function _verifyProof(
        bytes calldata _proof,
        bytes32 _nullifierHash,
        bytes32 _root,
        address _recipient,
        uint256 _amount
    ) internal view returns (bool) {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = abi.decode(
            _proof,
            (uint[2], uint[2][2], uint[2])
        );

        uint[4] memory pubSignals = [
            uint256(_root),
            uint256(_nullifierHash),
            uint256(uint160(_recipient)),
            _amount
        ];

        return verifier.verifyProof(pA, pB, pC, pubSignals);
    }

    // Allow contract to receive ETH
    receive() external payable {}
}
